# Generated by Django 3.2.13 on 2022-05-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tradingcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingcard',
            name='isListed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingcard',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tradingcard',
            name='ratingCount',
            field=models.IntegerField(default=0),
        ),
    ]
